name: toksearch_benchmark

channels:
  - conda-forge
  - ga-fdp

dependencies:
  - toksearch_d3d
  - jupyterlab=4.4.10
  - matplotlib=3.10.7
  - xarray=2025.10.1
  - scipy=1.16.3
  - netCDF4=1.7.3
  - pyspark=4.0.1
